# Generated by Django 6.0.2 on 2026-02-16 11:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SmallIntegerField(choices=[(1, 'Project'), (2, 'Legal'), (3, 'Technical'), (4, 'Finance')], unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('schema_json', models.JSONField()),
                ('version', models.PositiveIntegerField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='forms.formtype')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('form_type', 'version')},
            },
        ),
    ]
