# Generated by Django 5.2.11 on 2026-03-05 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_alter_projectmember_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=512)),
                ('file_type', models.SmallIntegerField(choices=[(1, 'txt'), (2, 'pdf'), (3, 'docx'), (4, 'xlsx')])),
                ('source_language', models.CharField(default='ja', max_length=10)),
                ('target_language', models.CharField(default='en', max_length=10)),
                ('source_s3_key', models.CharField(max_length=1024)),
                ('translated_s3_key', models.CharField(blank=True, default='', max_length=1024)),
                ('status', models.SmallIntegerField(choices=[(1, 'Uploaded'), (2, 'Translating'), (3, 'Completed'), (4, 'Failed')], default=1)),
                ('error_message', models.TextField(blank=True, default='')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='project.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine_used', models.CharField(max_length=100)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_logs', to='documents.document')),
            ],
        ),
    ]
